### ISSUE TITLE
Need to add try/except for file transfer to handle bug in ios ssh session mgmt

### ISSUE THREAD

**Issue by jmcgill298** [networktocode/pyntc#119]
https://github.com/networktocode/pyntc/blob/0601995dbcedcf7f0556459878e750f5c0574baf/pyntc/devices/ios_device.py#L219

Per https://github.com/networktocode/ntc-ansible/issues/242 and local testing, there needs to be a check upon receiving the following exception `raise socket.error(\"Socket is closed\")\nOSError: Socket is closed`. If this is received, then a follow up check should compare the hashes of the original file and the copy to see if the transfer was successful.

**Comment by mundruid** [comment]
Merged into develop.
