### ISSUE TITLE
pip3 install pyntc

### ISSUE THREAD

**Issue by hosseinoliabak** [networktocode/pyntc#14]
I am receiving the following error when installing pyntc for python 3. I have no issue with python 2. I tried 3 different Ubuntu Machines still the same message!
```
pip3 install pyntc
 Could not find a version that satisfies the requirement textfsm==1.0.1 (from pyntc) (from versions: 0.3.2)
No matching distribution found for textfsm==1.0.1 (from pyntc)
```
Please guide accordingly.
Regards,

**Comment by richwalker1988** [comment]
I too am having the same issue

please help

**Comment by lboue** [comment]
Hello,

I am facing the same issue on Ubuntu 17.10 too:
```
user@ubuntu:~$ uname -a
Linux ubuntu 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
user@ubuntu:~$ sudo pip3 install pyntc         
[sudo] password for user: 
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyntc
  Downloading pyntc-0.0.5.tar.gz
Collecting coverage (from pyntc)
  Downloading coverage-4.4.2-cp36-cp36m-manylinux1_x86_64.whl (197kB)
    100% |████████████████████████████████| 204kB 69kB/s 
Collecting future (from pyntc)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 236kB/s 
Collecting jsonschema (from pyntc)
  Downloading jsonschema-2.6.0-py2.py3-none-any.whl
Collecting mock>=1.3 (from pyntc)
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 64kB/s 
Collecting netmiko (from pyntc)
  Downloading netmiko-1.4.3.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 122kB/s 
Collecting paramiko (from pyntc)
  Downloading paramiko-2.4.0-py2.py3-none-any.whl (192kB)
    100% |████████████████████████████████| 194kB 183kB/s 
Collecting pyeapi==9.9.9 (from pyntc)
  Could not find a version that satisfies the requirement pyeapi==9.9.9 (from pyntc) (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.2, 0.3.3, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1)
No matching distribution found for pyeapi==9.9.9 (from pyntc)
```
I think pyeapi==9.9.9 is a mistake [here in the code ](https://github.com/networktocode/pyntc:/blob/4b115b83ece72be91dc6a94eca4819fa05a2c793/setup.py#L31) because the last release is [pyeapi ](https://pypi.python.org/pypi/pyeapi)0.8.1.

Could you fix this please?

Regards,
Ludovic

**Comment by lboue** [comment]
I have the same issue on Windows 7:

```
C:\Program Files\Python36>"C:\Program Files\Python36\Scripts\pip.exe" install pyntc-0.0.5.tar.gz
Processing c:\program files\python36\pyntc-0.0.5.tar.gz
Requirement already satisfied: requests>=2.7.0 in c:\program files\python36\lib\site-packages (from pyntc==0.0.5)
Collecting jsonschema (from pyntc==0.0.5)
  Using cached jsonschema-2.6.0-py2.py3-none-any.whl
Collecting future (from pyntc==0.0.5)
  Using cached future-0.16.0.tar.gz
Requirement already satisfied: netmiko in c:\program files\python36\lib\site-packages (from pyntc==0.0.5)
Requirement already satisfied: paramiko in c:\program files\python36\lib\site-packages (from pyntc==0.0.5)
Collecting pynxos>=0.0.3 (from pyntc==0.0.5)
  Using cached pynxos-0.0.3.tar.gz
Collecting coverage (from pyntc==0.0.5)
  Using cached coverage-4.4.2-cp36-cp36m-win_amd64.whl
Collecting mock>=1.3 (from pyntc==0.0.5)
  Using cached mock-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: terminal in c:\program files\python36\lib\site-packages (from pyntc==0.0.5)
Requirement already satisfied: textfsm==0.3.2 in c:\program files\python36\lib\site-packages (from pyntc==0.0.5)
Collecting pyeapi==9.9.9 (from pyntc==0.0.5)
  Could not find a version that satisfies the requirement pyeapi==9.9.9 (from pyntc==0.0.5) (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.2, 0.3.3, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1)
No matching distribution found for pyeapi==9.9.9 (from pyntc==0.0.5)
```

Regards,
Ludovic

**Comment by itdependsnetworks** [comment]
Sorry for the delay, will take a look shortly.

**Comment by smolz** [comment]
Still happening

**Comment by donotevercry** [comment]
Same problem here. 
pyntc 0.0.5 has requirement pyeapi==9.9.9, but you'll have pyeapi 0.8.2 which is incompatible.
pyntc 0.0.5 has requirement textfsm==1.0.1, but you'll have textfsm 0.4.1 which is incompatible.

**Comment by Mahsamtm** [comment]
I have same issue, appreciate your help
pip3 install ntc-ansible 
output:
.....
Collecting terminal (from pyntc->ntc-ansible)
  Using cached https://files.pythonhosted.org/packages/1d/33/063e9da9aca3fd67f9e9176483195cba970e320e7dc660018025ef4457de/terminal-0.4.0.tar.gz
Collecting pyeapi==9.9.9 (from pyntc->ntc-ansible)
  Could not find a version that satisfies the requirement pyeapi==9.9.9 (from pyntc->ntc-ansible) (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.2, 0.3.3, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1, 0.8.2)
No matching distribution found for pyeapi==9.9.9 (from pyntc->ntc-ansible)

installing on my mac, 
uname -a
Darwin m-C02SL0A4G8WM 15.6.0 Darwin Kernel Version 15.6.0: Mon Oct  2 22:20:08 PDT 2017; root:xnu-3248.71.4~1/RELEASE_X86_64 x86_64

**Comment by bradh11** [comment]
i too am having this issue - is there a fix for this yet?

`Could not find a version that satisfies the requirement pyeapi==9.9.9 (from pyntc) (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.2, 0.3.3, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1, 0.8.2)
No matching distribution found for pyeapi==9.9.9 (from pyntc)`

**Comment by jifox** [comment]
i'm also running into this error.

  Could not find a version that satisfies the requirement pyeapi==9.9.9 (from pyntc) (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.2, 0.3.3, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1, 0.8.2)
No matching distribution found for pyeapi==9.9.9 (from pyntc)


# python --version
Python 3.6.3


# uname -a
Linux ansible.local 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sachin0987** [comment]
Hey Guyz, 

There is any solution for that as I am too getting same issue .

**Comment by jmcgill298** [comment]
Fixed in https://github.com/networktocode/pyntc/commit/c1d6b79f4b8d08edcfaa7556aa63ac6fb03fc19f
