### ISSUE TITLE
Python 2 doesn't support sys.version.major

### ISSUE THREAD

**Issue by MTWiley** [networktocode/pyntc#15]
https://github.com/networktocode/pyntc/blob/a3990f864d8b0d5828a3f5eb543c7c525381844d/setup.py#L29

Could be changed to change to sys.version[0] to accomplish the same thing and support both python2 and python3.

**Comment by itdependsnetworks** [comment]
Do you mind putting in a PR?

**Comment by MTWiley** [comment]
https://github.com/networktocode/pyntc/pull/16

**Comment by jmcgill298** [comment]
@MTWiley can you try now?
