### ISSUE TITLE
Add docstrings to major functions in devices

### ISSUE THREAD

**Issue by mundruid** [networktocode/pyntc#164]
We need more documentation of arguments for old devices that have not been added recently (ios, nxos, etc.)

**Comment by qduk** [comment]
Hey Dr.X @mundruid, thoughts on closing this now that all my docstring PRs have been merged?

**Comment by mundruid** [comment]
> Hey Dr.X @mundruid, thoughts on closing this now that all my docstring PRs have been merged?

Absolutely! Thank you for doing all this work, @qduk
