### ISSUE TITLE
Merge config_list into config method

### ISSUE THREAD

**Issue by jmcgill298** [networktocode/pyntc#176]
The config_list method should be merged into the config method to simplify the interface

**Comment by jeffkala** [comment]
@jmcgill298, both options should still be allowed correct?  We just want to dynamically determine the data that was sent?  `.config("hostname test")` or `.config(["hostname test"])`.

Was thinking I'd give this one a shot.

**Comment by jmcgill298** [comment]
correct, this is will be handled for all netmiko devices in the `netmiko_base` branch. So this would need to be done in F5, EOS, and Juniper drivers (NXOS will migrate to use netmiko once we have the netmiko base class). You can see the implementation for netmiko here `https://github.com/networktocode/pyntc/blob/4e56dfcede757a393e0d1caaa44c46539d949362/pyntc/devices/base_netmiko.py`

Feel free to book some time with me if you would like to go over it before you get started.

**Comment by jeffkala** [comment]
@jmcgill298 since F5, EOS, JUNOS are merged for the config methods, should we close this issue?  Or should I use this same issue for the show merges?

**Comment by jmcgill298** [comment]
We will close this one, thanks @jeffkala
