### ISSUE TITLE
Deprecate config_list and show_list in ASA, EOS, JunOS and F5

### ISSUE THREAD

**Issue by jmcgill298** [networktocode/pyntc#185]
Functionality supported by config_list and show_list methods should be added to config_list and show_list methods respectively, and warning of deprecation should be added for the *_list methods

ASA:
- [x] migrate config_list to config
- [x] migrate show_list to show
- [x] add warnings of deprecation to *_list methods

EOS:
- [x] migrate config_list to config
- [x] migrate show_list to show
- [x] add warnings of deprecation to *_list methods

JunOS:
- [x] migrate config_list to config
- [x] migrate show_list to show
- [x] add warnings of deprecation to *_list methods

F5:
- [x] migrate config_list to config
- [x] migrate show_list to show
- [x] add warnings of deprecation to *_list methods

**Comment by jeffkala** [comment]
These have been completed. By #269
