### ISSUE TITLE
Review all code to get pylint to pass

### ISSUE THREAD

**Issue by jeffkala** [networktocode/pyntc#249]
Currently with new dev standards implemented all updates to the code have been made to get all test to pass except pylint which is going to be a heavy lift to get passing.

Need to get this test passing before next release using GHA.

**Comment by jeffkala** [comment]
@jvanderaa was going to attempt to cover this.

**Comment by jvanderaa** [comment]
✅ DONE!

**Comment by jeffkala** [comment]
closed in #282
