### ISSUE TITLE
getting error while installing pyntc, please support

### ISSUE THREAD

**Issue by abbaskw123** [networktocode/pyntc#265]
PS D:\Python> pip install pyntc   
Collecting pyntc
  Using cached pyntc-0.20.3-py3-none-any.whl (66 kB)
Collecting f5-sdk<4.0.0,>=3.0.21
  Using cached f5-sdk-3.0.21.tar.gz (156 kB)
  Preparing metadata (setup.py) ... done
Collecting importlib-metadata==4.13.0
  Using cached importlib_metadata-4.13.0-py3-none-any.whl (23 kB)
Collecting junos-eznc<3.0,>=2.6
  Using cached junos_eznc-2.6.5-py2.py3-none-any.whl (197 kB)
Requirement already satisfied: netmiko<5.0,>=4.0 in c:\python\python.3.11\lib\site-packages (from pyntc) (4.1.2)
Requirement already satisfied: pyeapi<0.9.0,>=0.8.4 in c:\python\python.3.11\lib\site-packages (from pyntc) (0.8.4)
Collecting pynxos<0.0.6,>=0.0.5
  Using cached pynxos-0.0.5.tar.gz (7.9 kB)
  Preparing metadata (setup.py) ... done
Collecting requests<3.0,>=2.28
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Requirement already satisfied: scp<0.15,>=0.14 in c:\python\python.3.11\lib\site-packages (from pyntc) (0.14.4)
Requirement already satisfied: zipp>=0.5 in c:\python\python.3.11\lib\site-packages (from importlib-metadata==4.13.0->pyntc) (3.10.0)
Requirement already satisfied: six>=1.9.0 in c:\python\python.3.11\lib\site-packages (from f5-sdk<4.0.0,>=3.0.21->pyntc) (1.16.0)
Collecting f5-icontrol-rest>=1.3.13
  Using cached f5-icontrol-rest-1.3.13.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Collecting lxml>=3.2.4
  Using cached lxml-4.9.1.tar.gz (3.4 MB)
  Preparing metadata (setup.py) ... done
Collecting ncclient==0.6.13
  Using cached ncclient-0.6.13.tar.gz (105 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: paramiko>=1.15.2 in c:\python\python.3.11\lib\site-packages (from junos-eznc<3.0,>=2.6->pyntc) (2.12.0)
Collecting jinja2>=2.7.1
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Requirement already satisfied: PyYAML>=5.1 in c:\python\python.3.11\lib\site-packages (from junos-eznc<3.0,>=2.6->pyntc) (6.0)
Requirement already satisfied: netaddr in c:\python\python.3.11\lib\site-packages (from junos-eznc<3.0,>=2.6->pyntc) (0.8.0)
Requirement already satisfied: pyserial in c:\python\python.3.11\lib\site-packages (from junos-eznc<3.0,>=2.6->pyntc) (3.5)
Requirement already satisfied: yamlordereddictloader in c:\python\python.3.11\lib\site-packages (from junos-eznc<3.0,>=2.6->pyntc) (0.4.0)
Requirement already satisfied: pyparsing in c:\python\python.3.11\lib\site-packages (from junos-eznc<3.0,>=2.6->pyntc) (3.0.9)
Requirement already satisfied: transitions in c:\python\python.3.11\lib\site-packages (from junos-eznc<3.0,>=2.6->pyntc) (0.9.0)
Requirement already satisfied: setuptools>0.6 in c:\python\python.3.11\lib\site-packages (from ncclient==0.6.13->junos-eznc<3.0,>=2.6->pyntc) (65.5.0)
Requirement already satisfied: tenacity in c:\python\python.3.11\lib\site-packages (from netmiko<5.0,>=4.0->pyntc) (8.1.0)
Requirement already satisfied: textfsm==1.1.2 in c:\python\python.3.11\lib\site-packages (from netmiko<5.0,>=4.0->pyntc) (1.1.2)
Requirement already satisfied: ntc-templates>=2.0.0 in c:\python\python.3.11\lib\site-packages (from netmiko<5.0,>=4.0->pyntc) (3.1.0)
Requirement already satisfied: future in c:\python\python.3.11\lib\site-packages (from textfsm==1.1.2->netmiko<5.0,>=4.0->pyntc) (0.18.2)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python\python.3.11\lib\site-packages (from requests<3.0,>=2.28->pyntc) (1.26.13)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python\python.3.11\lib\site-packages (from jinja2>=2.7.1->junos-eznc<3.0,>=2.6->pyntc) (2.1.1)
Requirement already satisfied: bcrypt>=3.1.3 in c:\python\python.3.11\lib\site-packages (from paramiko>=1.15.2->junos-eznc<3.0,>=2.6->pyntc) (4.0.1)
Requirement already satisfied: cryptography>=2.5 in c:\python\python.3.11\lib\site-packages (from paramiko>=1.15.2->junos-eznc<3.0,>=2.6->pyntc) (38.0.3)
Requirement already satisfied: pynacl>=1.0.1 in c:\python\python.3.11\lib\site-packages (from paramiko>=1.15.2->junos-eznc<3.0,>=2.6->pyntc) (1.5.0)
Requirement already satisfied: cffi>=1.12 in c:\python\python.3.11\lib\site-packages (from cryptography>=2.5->paramiko>=1.15.2->junos-eznc<3.0,>=2.6->pyntc) (1.15.1)
Requirement already satisfied: pycparser in c:\python\python.3.11\lib\site-packages (from cffi>=1.12->cryptography>=2.5->paramiko>=1.15.2->junos-eznc<3.0,>=2.6->pyntc) (2.21)
Installing collected packages: lxml, jinja2, importlib-metadata, idna, charset-normalizer, certifi, requests, f5-icontrol-rest, ncclient, f5-sdk, pynxos, junos-eznc, pyntc
  DEPRECATION: lxml is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for lxml ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for lxml did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      Building lxml version 4.9.1.
      Building without Cython.
      Building against pre-built libxml2 andl libxslt libraries
      running install
      C:\Python\Python.3.11\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\builder.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\cssselect.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\doctestcompare.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\ElementInclude.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\sax.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\usedoctest.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\_elementpath.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\__init__.py -> build\lib.win-amd64-cpython-311\lxml
      creating build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\__init__.py -> build\lib.win-amd64-cpython-311\lxml\includes
      creating build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\builder.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\clean.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\defs.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\diff.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\formfill.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\html5parser.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\soupparser.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\__init__.py -> build\lib.win-amd64-cpython-311\lxml\html
      creating build\lib.win-amd64-cpython-311\lxml\isoschematron
      copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-cpython-311\lxml\isoschematron
      copying src\lxml\etree.h -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\etree_api.h -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\lxml.etree.h -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\config.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\__init__.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-cpython-311\lxml\includes
      creating build\lib.win-amd64-cpython-311\lxml\isoschematron\resources
      creating build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\rng
      copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\rng
      creating build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl
      copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl
      copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl
      creating build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1      
      running build_ext
      building 'lxml.etree' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by jeffkala** [comment]
Py3.10, Py3.11 isn't supported yet due to an upstream dependency issue.

**Comment by abbaskw123** [comment]
thank you so much, it's working with older version.

**Comment by jeffkala** [comment]
https://github.com/networktocode/pyntc/issues/256
