### ISSUE TITLE
Use of signal in ios_device during reboot, limits the ability to run within threads.

### ISSUE THREAD

**Issue by jeffkala** [networktocode/pyntc#274]
https://github.com/networktocode/pyntc/blob/c9c1a9d3e965b1998103ca59e0fd2244fbd8eac1/pyntc/devices/ios_device.py#L920

I don't see this being required, we have some other methods now to determine when a device is back up after a reboot.  @jmcgill298 do you know the original reason `signal` was used here(within cisco devices) and not in any of the other device drivers?

**Comment by jmcgill298** [comment]
@jeffkala I think this is used to force a reset stale ssh sessions once the channel has been broken by the reboot.
