### ISSUE TITLE
backup running config returns "building configuration..." on IOS

### ISSUE THREAD

**Issue by mzbenami** [networktocode/pyntc#3]
Probably related to netmiko delay factor or send_command_expected

**Comment by petehoffswell** [comment]
Verification:

`>>> from netmiko import ConnectHandler
>>> net_connect = ConnectHandler(device_type='cisco_ios', ip='x.x.x.x', username='xxx', password='xxx')
SSH connection established to x.x.x.x:22
Interactive SSH session established
>>> net_connect.find_prompt()
u'SWITCH#'
>>> output = net_connect.send_command("show run")
>>> print output
Building configuration...

>>>`

**Comment by petehoffswell** [comment]
This also effects
https://github.com/networktocode/ntc-ansible
