### ISSUE TITLE
Fix EOS Unit Tests

### ISSUE THREAD

**Issue by jmcgill298** [networktocode/pyntc#86]
Currently 3 tests are failing for EOS:
 
- [x] [test_file_copy_remote_exists](https://github.com/networktocode/pyntc/blob/0601995dbcedcf7f0556459878e750f5c0574baf/test/unit/test_devices/test_eos_device.py#L98)
- [x] [test_file_copy](https://github.com/networktocode/pyntc/blob/0601995dbcedcf7f0556459878e750f5c0574baf/test/unit/test_devices/test_eos_device.py#L112)
- [x] [test_set_boot_options](https://github.com/networktocode/pyntc/blob/0601995dbcedcf7f0556459878e750f5c0574baf/test/unit/test_devices/test_eos_device.py#L134)

**Comment by mundruid** [comment]
* All 25 tests passed
* We may want to consider converting from unittest to pytest
