### ISSUE TITLE
Automatically generate and publish docs

### ISSUE THREAD

**Issue by jmcgill298** [networktocode/pyntc#91]
- [x] Add tests for pydocstyle
- [ ] Update all missing or insufficient documentation
- [ ] Add sphinx
- [ ] Add readthedocs

**Comment by jmcgill298** [comment]
#164 for updating docstrings

**Comment by jmcgill298** [comment]
#97 for pydocstyle

**Comment by jeffkala** [comment]
Publishes to read the docs via mkdocs with new standard.
https://pyntc.readthedocs.io/en/latest/
