### ISSUE TITLE
Update Tox to have multiple environments

### ISSUE THREAD

**Issue by jmcgill298** [networktocode/pyntc#97]
Tox file should include tests for things like formatting and styling

**Comment by qduk** [comment]
@jmcgill298  Thoughts on closing this? I'm not sure if pydocstyle was the only requirement you had in mind for this issue. Let me know!

**Comment by jmcgill298** [comment]
The travis file should also be updated to run each lint stage simultaneously and before the unit tests. Look at [ntc-templates](https://github.com/networktocode/ntc-templates/blob/master/.travis.yml)
